### ISSUE TITLE
Re add “compile all scripts” option

### ISSUE THREAD

**Issue by TheMaskedMan00** [vrchat-community/UdonSharp#109]
Re add option to not compile all scripts every time one script changes.

Also, whenever changing a script that isn’t related to udonsharp, it compiles all udon sharp behaviours anyways. I have a slow laptop and a lot of udon in my project and it takes a long time. Could you add an option that can stop udonsharp from compiling when a non udon script is changed?

the docs also still show the setting I mentioned 
![298AD172-696D-4A5A-8346-C80C46B76322](https://user-images.githubusercontent.com/46354545/220708779-00916abe-28a7-4c53-a0cb-19ccf8bf5ebe.jpeg)

**Comment by MerlinVR** [comment]
This doesn't work anymore with U#'s architecture and was removed as a result. U# needs awareness of all scripts that it may reference because users could define static functions or other things that U# needs to be able to see. You can disable auto compile on modify if you want, that will not trigger compiles until they are absolutely needed.
