### ISSUE TITLE
Migration of prefab with UdonSharp 0.20.3 project to 1.x is broken

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/UdonSharp#58]
**Describe the bug in detail:**

Migrating prefab made with UdonSharp 0.20.3 to 1.x is broken in some case.
In similar case, prefab with UdonGraph will not be broken so I think this is bug of UdonSharp.

**Provide steps/code to reproduce the bug:**

1. create/open project with UdonSharp 1.x.
1. import UdonSharpTest.unitypackage in [UdonSharpTest.unitypackage.zip][test-package-zip]

**Expected behavior:**

In `1.OuterObject/2.InnerObject` of `UdonSharpTest/1.OuterObject.prefab`, the value of `Test Color` is black (as if we imported to project with old SDK).

**Actual behavior:**

In `1.OuterObject/2.InnerObject` of `UdonSharpTest/1.OuterObject.prefab`, the value of `Test Color` is white, the color specified in `2.InnerObject.prefab`.

**Additional Information:**

In `3.InnerObject.prefab`, `Test Color` is black, as we imported to old SDK.

[test-package-zip]: https://github.com/vrchat-community/UdonSharp/files/9388878/UdonSharpTest.unitypackage.zip

**Comment by MerlinVR** [comment]
Nested prefabs and prefab variants do not have an automatic upgrade path and will need to be fixed manually if they break. This is because having support for upgrading them would complicate the upgrade process significantly which could cause the supported cases to break and they weren't supported prior to 1.0.
